#!/usr/bin/env node
/**
 * Inject Doppler Secrets
 *
 * Generates a secrets file from Doppler environment variables.
 * Run: doppler run -- node scripts/inject-secrets.js
 */

const fs = require('fs');
const path = require('path');

const secrets = {
  ANTHROPIC_API_KEY: process.env.ANTHROPIC || process.env.ANTHROPIC_API_KEY || ''
};

const output = `// Auto-generated by Doppler - do not edit manually
window.__DOPPLER_SECRETS__ = ${JSON.stringify(secrets, null, 2)};
`;

const outputPath = path.join(__dirname, '..', 'doppler-secrets.js');
fs.writeFileSync(outputPath, output);

console.log('Secrets injected to doppler-secrets.js');
